---
- name: remove old docker
  apt:
    name: "{{ item }}"
    state: removed
    purge: yes
  with_items:
     - docker
     - docker-engine
- name: install docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - apt-transport-https
    - ca-certificates
    - software-properties-common
- name: add docker’s official GPG key
  apt_key: 
    id: 0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
- name: set up the stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    update_cache: yes
- name: install docker-ce
  apt:
    name: docker-ce
    state: present
- name: add user mod
  user:
    name: "{{remote_user}}"
    groups: docker
    append: yes
